name: Feature request
description: Propose a new capability or improvement.
title: "[feature]: <short summary>"
labels:
  - enhancement
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: One sentence describing the request
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What's the user problem or job-to-be-done?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: API/UX sketch, constraints, tradeoffs.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: dropdown
    id: area
    attributes:
      label: Affected area/component
      multiple: false
      options:
        - bundling
        - downloads
        - terminal
        - ui
        - docs
        - npm logic
