blank_issues_enabled: false
contact_links:
    - name: README
      url: https://github.com/t128n/packy#readme
      about: Start here for project context and setup notes.
    - name: CONTRIBUTING
      url: https://github.com/t128n/packy#contributing
      about: Learn how to contribute to packy.
